#!/usr/bin/env python3
"""
Build only C++ libraries and Cython extensions without installing or testing.
This is used by the Hatch build system which handles packaging separately.

Usage:
    build_libs_only.py VERSION [--fast]
"""

import sys
import os
import subprocess

# Add tools directory to path so we can import from build.py
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

# Import everything from build.py
import build
from build import (
    command_line_args, check_cython_version, check_directories,
    setup_environ, clear_cache, copy_and_fix_pyx_files,
    build_cefpython_module, fix_cefpython_api_header_file,
    compile_cpp_projects_with_setuptools, compile_cpp_projects_unix,
    CEFPYTHON_API_HFILE
)
import platform
from common import ARCH_STR, PYVERSION, OS_POSTFIX2, TOOLS_DIR, WINDOWS, MAC, LINUX


def main():
    """Build C++ and Cython only, skip install and tests."""
    command_line_args()
    print("[build_libs_only.py] Python version: {ver} {arch}"
          .format(ver=platform.python_version(), arch=ARCH_STR))
    print("[build_libs_only.py] Python executable: %s" % sys.executable)
    print("[build_libs_only.py] PYVERSION = %s" % PYVERSION)
    print("[build_libs_only.py] OS_POSTFIX2 = %s" % OS_POSTFIX2)
    check_cython_version()
    check_directories()
    setup_environ()

    # Check if this is first run (cefpython_pyXX.h doesn't exist yet)
    first_run = not os.path.exists(CEFPYTHON_API_HFILE)
    if first_run:
        print("[build_libs_only.py] INFO: First run detected, as"
              " cefpython_py{pyver}.h is missing."
              .format(pyver=PYVERSION))
        # NOTE: We intentionally do NOT set build.FIRST_RUN = True here.
        # build_cefpython_module() has re-run logic that would incorrectly
        # re-run build.py instead of build_libs_only.py. By not setting
        # FIRST_RUN, we let it fail with sys.exit(1) and handle the
        # re-run ourselves below.
    else:
        # Not first run - the _fixed.h file exists, so we can build C++ projects
        fix_cefpython_api_header_file()
        if WINDOWS:
            compile_cpp_projects_with_setuptools()
        elif MAC or LINUX:
            compile_cpp_projects_unix()

    clear_cache()
    copy_and_fix_pyx_files()

    # Run the cython build - this may fail on first run because the
    # cefpython_pyXX_fixed.h header doesn't exist yet. On first run,
    # Cython will still generate cefpython_pyXX.h before failing at
    # the C++ compilation step.
    try:
        build_cefpython_module()
    except SystemExit as e:
        if first_run and os.path.exists(CEFPYTHON_API_HFILE):
            # First run failed but .h file was generated by Cython.
            # Create the _fixed.h file and re-run ourselves.
            print("[build_libs_only.py] INFO: First run build failed as expected.")
            print("[build_libs_only.py] INFO: Creating fixed header and re-running...")
            fix_cefpython_api_header_file()

            # Re-run this script
            args = [sys.executable, os.path.join(TOOLS_DIR, "build_libs_only.py")]
            args.extend(sys.argv[1:])
            print("[build_libs_only.py] Running: %s" % " ".join(args))
            ret = subprocess.call(args)
            sys.exit(ret)
        else:
            raise

    fix_cefpython_api_header_file()

    print("\n" + "="*60)
    print("[build_libs_only.py] Build completed successfully")
    print("[build_libs_only.py] Skipping install and tests")
    print("[build_libs_only.py] Wheel will be created by Hatch")
    print("="*60 + "\n")


if __name__ == "__main__":
    main()
